<?php
$ow = OntoWiki::getInstance();
$this->headScript()->appendFile($ow->extensionManager->getComponentUrl('map')."classes/OpenLayers.js");
// TODO: check if exconf is available
$this->headScript()->appendFile($ow->extensionManager->getComponentUrl('exconf')."resources/jquery.togglebutton.js");
$this->headLink()->appendStylesheet($ow->extensionManager->getComponentUrl('exconf')."resources/togglebutton.css");

if ( isset($this->message) ) {
        echo '<p class="messagebox info">' . $this->_($this->message) . '</p>';
}
?>

<script type="text/javascript">
//<![CDATA[

    function postToggle(button)
    {
        var name = $(button).parent().attr("id");
        var enabled = $(button).attr("selected");
        /*$.post(urlBase + "exconf/conf/?name="+name+"&enabled="+enabled,function(data){if(data==""){$("#numEnabled").html(parseInt($("#numEnabled").html())+( enabled == "true" ? 1 : -1));$("#numDisabled").html(parseInt($("#numDisabled").html())+( enabled == "true" ? -1 : 1));}});*/
    }

$(function()
{
    $(".togglebutton").togglebutton(
        {"onEnable":
            postToggle,
         "onDisable":
            postToggle
        }
    );
});

//]]>
</script>


<h1><?php echo $this->_('Map Extension Configuration') ?></h1>

<!-- Later the form should be send with and ajax request -->
<form action="<?php echo $this->urlBase;?>exconf/conf" method="POST">
    <input type="hidden" name="name" value="map" />
    <fieldset>
        <legend><?php echo $this->_('Info') ?></legend>
        <div>
            <table class="separated-vertical">
                <tr>
                    <th><?php echo $this->_('OpenLayers Version') ?></th>
                    <td id="ol_version"></td>
                </tr>
            </table>
        </div>
    </fieldset>

    <fieldset>
        <legend><?php echo $this->_('General Settings')?></legend>
        <div>
            <table class="separated-vertical">
                <tr>
                    <th><?php echo $this->_('Show Map Tab')?></th>
                    <td>
                        <select name="show.tab">
                            <?php foreach ($this->config->show->_tab as $option): ?>
                            <?php
                                if($this->config->show->tab == $option) {
                                    $sel = true;
                                } else {
                                    $sel = false;
                                }
                            ?>
                            <option value="<?php echo $this->escape($option) ?>" <?php echo $sel?'selected="true"':'' ?>><?php echo $this->escape($option) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <th><?php echo $this->_('Default Layer') ?></th>
                    <td>
                        <select name="default.layer">
                            <?php foreach ($this->config->default->_layer as $option): ?>
                            <?php
                                if($this->config->default->layer == $option) {
                                    $sel = true;
                                } else {
                                    $sel = false;
                                }
                            ?>
                            <option value="<?php echo $this->escape($option) ?>" <?php echo $sel?'selected="true"':'' ?>><?php echo $this->escape($option) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <th><?php echo $this->_('Home')?></th>
                    <td>
                        <table>
                            <tr>
                                <th><?php echo $this->_('Latitude')?></th>
                                <td>
                                    <input class="text width99" type="text" name="default.latitude" value="<?php echo $this->escape($this->config->default->latitude) ?>" />
                                </td>
                            </tr>
                            <tr>
                                <th><?php echo $this->_('Longitude')?></th>
                                <td>
                                    <input class="text width99" type="text" name="default.longitude" value="<?php echo $this->escape($this->config->default->longitude) ?>" />
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
    </fieldset>

    <fieldset>
        <legend><?php echo $this->_('Map Providers')?></legend>
        <div>
            <table class="separated-vertical">
                <tr>
                    <th><?php echo $this->_('Provider')?></th>
                    <th><?php echo $this->_('Enabled')?></th>
                    <th><?php echo $this->_('API-Key')?></th>
                </tr>
                <!--//
                <tr id="newKey">
                    <td>
                        <input class="text" type="text" name="newMapProvider" />
                    </td>
                    <td>
                        <input class="text" type="text" name="newMapKey" />
                    </td>
                </tr>
                //-->
                <?php foreach ($this->config->load as $provider => $enabled): ?>
                <tr>
                    <td><?php echo $this->escape($provider) ?></td>
                    <td><div class="togglebutton" <?php if(isset($enabled) && $enabled){ echo "selected=\"true\""; } ?>></div></td>
                    <!--<td><div class="togglebutton" selected="true" ></div></td>-->
                    <td>
                        <?php $key = $this->config->apikey->$provider; ?>
                        <input class="text width99" type="text" name="apikey.<?php echo $this->escape($provider) ?>" value="<?php echo $this->escape($key) ?>" />
                    </td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
        <div class="clearall"></div>
    </fieldset>

    <fieldset>
        <legend><?php echo $this->_('Local Map')?></legend>
        <div>
            <table class="separated-vertical">
                <tr>
                    <th><?php echo $this->_('Titel')?></th>
                    <td>
                        <input class="text width99" type="text" name="localMap.titel" value="<?php echo $this->escape($this->config->localMap->titel) ?>" />
                    </td>
                </tr>
                <tr>
                    <th><?php echo $this->_('URL')?></th>
                    <td>
                        <input class="text width99" type="text" name="localMap.url" value="<?php echo $this->escape($this->config->localMap->url) ?>" />
                    </td>
                </tr>
            </table>
        </div>
        <div class="clearall"></div>
    </fieldset>

    <!-- TODO: Clusterer and multiple Properties -->

    <?php $confStr = json_encode(array('enabled'=>true, 'private'=>$this->configArray)); ?>
    <textarea name="config"><?php echo $confStr; ?></textarea> <br/>
    <input type="submit" name="send" value="senden"/>
</form>

<script type="text/javascript">
//<![CDATA[
    $('#ol_version').text(OpenLayers.VERSION_NUMBER);
//]]>
</script>

hier ein minimal working example - direkt in json rumschreiben...<br/>
alternativ kann man eine schöne gui machen die am ende den json string in die passenden post parameter packt.<br/>
nur der enabled wert und und die private config kann geändert werden. <br/>
mann muss eingeloggt sein damit es funktioniert. es wird ajax empfohlen weil man sonst auf der standard config seite landet.
