<?php

/**
 * OntoWiki model list template
 *
 * @version $Id: geocode.phtml $
 */

?>
<?php if ( isset($this->message) ): ?>
<!-- war mal div -->
<p class="messagebox info" id="geocode-warning"><?php echo $this->_($this->message); ?></p>
<?php endif; ?>

<form id="minimapsearch">
    <p class="width98">
        <label class="display-block" for="minimapsearch-input"><?php echo $this->_('Search for location') ?></label>
        <input class="text width99 inner-label" type="text" id="minimapsearch-input" name="location" />
        <!-- maybe we should show a button for some touch devices -->
        <!-- <a class="button" id="geocode-button"><span><?php echo $this->_('Go') ?></span></a> -->
    </p>
</form>

<div id="geocode-resultlist" style="display: none;"></div>
<div id="geocode-form">

<?php
    $htmlPartialUrl = new OntoWiki_Url(array('controller' => 'map', 'action' => 'geocode'));
    $htmlPartialUrl->setParam('q', '__searchstring__', true);
?>

<script type="text/javascript">

$(document).ready(function()
{
    var htmlPartialUrl = '<?php echo $htmlPartialUrl; ?>';

    var geocode = new GeocodeManager();

    $('#geocode-button').click(function(event)
    {
        geocode.doGeocode($('#minimapsearch-input').val());
    });

    $("#minimapsearch-input").keypress(function (e)
    {
        if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
            geocode.doGeocode($('#minimapsearch-input').val());
            return false;
        } else {
            return true;
        }
    });

});

</script>
</div>
