<?php

/**
 * OntoWiki model list template
 *
 * @version $Id: quickstats.phtml $
 */

#var_dump($this->data);
?>
<div id="quickstats-content" about="<?php echo $this->stats['resourceUri'] ?>">

<?php echo $this->_('Overall Resources (POIs) ') ?> (<?php echo $this->stats['typedResources'] ?>)<br />
<?php echo $this->_('Resources with coordinates') ?> (<?php echo $this->stats['with_coords'] ?>)<br />
<a href="../../list/init/1/?m=http%3A%2F%2Fvakantieland.nl%2F&instancesconfig=%7B%22filter%22%3A%5B%7B%22action%22%3A%22add%22%2C%22mode%22%3A%22box%22%2C%22id%22%3A%22filterbox0%22%2C%22property%22%3A%22http%3A%5C%2F%5C%2Fns.aksw.org%5C%2FspatialFeatures%5C%2Faccuracy%22%2C%22isInverse%22%3Afalse%2C%22propertyLabel%22%3A%22Accuracy%22%2C%22filter%22%3A%22smaller%22%2C%22value1%22%3A%220%22%2C%22value2%22%3Anull%2C%22valuetype%22%3A%22typed-literal%22%2C%22literaltype%22%3A%22http%3A%5C%2F%5C%2Fwww.w3.org%5C%2F2001%5C%2FXMLSchema%23integer%22%2C%22hidden%22%3Afalse%2C%22negate%22%3Afalse%2C%22objects%22%3A%5B%7B%7D%2Cnull%5D%7D%5D%7D"><?php echo $this->_('Ressources without position') ?></a> (<?php echo $this->stats['without_coords'] ?>)<br />

<a href="../../list/init/1/?m=http%3A%2F%2Fvakantieland.nl%2F&instancesconfig=%7B%22filter%22%3A%5B%7B%22action%22%3A%22add%22%2C%22mode%22%3A%22box%22%2C%22id%22%3A%22filterbox0%22%2C%22property%22%3A%22http%3A%5C%2F%5C%2Fns.aksw.org%5C%2FspatialFeatures%5C%2Faccuracy%22%2C%22isInverse%22%3Afalse%2C%22propertyLabel%22%3A%22Accuracy%22%2C%22filter%22%3A%22smaller%22%2C%22value1%22%3A%226%22%2C%22value2%22%3Anull%2C%22valuetype%22%3A%22typed-literal%22%2C%22literaltype%22%3A%22http%3A%5C%2F%5C%2Fwww.w3.org%5C%2F2001%5C%2FXMLSchema%23integer%22%2C%22hidden%22%3Afalse%2C%22negate%22%3Afalse%2C%22objects%22%3A%5B%7B%7D%2Cnull%5D%7D%5D%7D"><?php echo $this->_('Low accuracy (between 0 and 6)') ?></a> (<?php echo $this->stats['low_accuracy'] ?>)<br />

<a href="../../list/init/1/?m=http%3A%2F%2Fvakantieland.nl%2F&instancesconfig=%7B%22filter%22%3A%5B%7B%22action%22%3A%22add%22%2C%22mode%22%3A%22box%22%2C%22id%22%3A%22filterbox0%22%2C%22property%22%3A%22http%3A%5C%2F%5C%2Fns.aksw.org%5C%2FspatialFeatures%5C%2Faccuracy%22%2C%22isInverse%22%3Afalse%2C%22propertyLabel%22%3A%22Accuracy%22%2C%22filter%22%3A%22smaller%22%2C%22value1%22%3A%220%22%2C%22value2%22%3Anull%2C%22valuetype%22%3A%22typed-literal%22%2C%22literaltype%22%3A%22http%3A%5C%2F%5C%2Fwww.w3.org%5C%2F2001%5C%2FXMLSchema%23integer%22%2C%22hidden%22%3Afalse%2C%22negate%22%3Afalse%2C%22objects%22%3A%5B%7B%7D%2Cnull%5D%7D%5D%7D"><?php echo $this->_('Ressources geocoded via postcode') ?></a> (<?php echo $this->stats['postcode_geocoded'] ?>)

</div>
