<?php
/**
 * OntoWiki minimap module template
 */
?>
<div id="miniMap" class="is-processing width99">
</div>
<script type="text/javascript">

<?php
    $htmlPartialUrl = new OntoWiki_Url(array('controller' => 'map', 'action' => 'display'));
    $htmlPartialUrl->setParam('inline', true);
    if (isset($this->context) && $this->context == 'single_instance') {
        $htmlPartialUrl->setParam('single_instance', 'on', true);
    }
?>

$.get(
    '<?= $htmlPartialUrl ?>',
    function (data)
    {
        $('#miniMap').removeClass('is-processing');
        $('#miniMap').html(data);
    }
);
</script>
