<?php
// vim: sw=4:sts=4:expandtab
/**
 * OntoWiki minimap module template
 *
 * @version $Id: showproperties.phtml 4143 2009-09-08 12:26:52Z jonas.brekle $
 */
?>

<form id="minimapsearch">
    <p class="width98">
        <label class="display-block" for="minimapsearch-input"><?php echo $this->_('Search for location') ?></label>
        <input class="text width99 inner-label" type="text" id="minimapsearch-input" name="location" />
    </p>
</form>

<?php if ( isset($this->message) ): ?>
<p class="messagebox info"><?php echo $this->_($this->message); ?></p>
<?php endif; ?>
<div id="miniMap" class="is-processing width99">
</div>
<script type="text/javascript">

//    $('#miniMap').addClass('is-processing');
//    $('#miniMap').addClass('width99');
//    $('#miniMap').height( $('#miniMap').width() ); 

<?php
    $htmlPartialUrl = new OntoWiki_Url(array('controller' => 'map', 'action' => 'display'));
    $htmlPartialUrl->setParam('inline', true);
    if (isset($this->context) && $this->context == 'single_instance') {
        $htmlPartialUrl->setParam('single_instance', 'on', true);
    }
?>

$.get(
    '<?php echo $htmlPartialUrl; ?>',
    function (data)
    {
        $('#miniMap').removeClass('is-processing');
        $('#miniMap').html(data);
    }
);
</script>
